name: Dependabot pull requests

on: pull_request

jobs:
  dependabot:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    if:  ${{github.event.pull_request.user.login == 'dependabot[bot]'}}
    permissions:
      pull-requests: write
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_URL: ${{ github.event.pull_request.html_url }}
    steps:
      - name: Fetch Dependabot Metadata
        uses: dependabot/fetch-metadata@v2
        id: dependabot-metadata
      - name: Approve and Merge the PR
        # Don't do this for the container-updates group
        if: ${{ steps.dependabot-metadata.outputs.dependency-group != 'container-updates' }}
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --squash --auto "$PR_URL"
