name: Run Tests

on: push

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Create .env file
        run: cat env.* > .env
      - name: Load .env file
        uses: xom9ikk/dotenv@ac290ca23a42155a0cba1031d23afa46240116a9 # v2.3.0
      - name: Set up Ruby 3.3
        uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f # v1.295.0
        with:
          ruby-version: 3.3
          bundler-cache: true
      - name: Run linter for Ruby
        run: bundle exec standardrb
      - name: Run tests
        run: bundle exec rspec
